from scraper.parser import Tweet, TwitterParser
from typing import List

def test_parser():
  parser = TwitterParser()
  with open("test/scraper/test.html", 'r') as fh:
    contents: str = fh.read()
  assert(contents)

  parser.feed(contents)
  tweets: List[Tweet] = parser.tweets
  assert(len(tweets) == 30)

  should_be = [{'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': "With their preparations finished and the day upon them, it's time for the Mighty Nein's greatest challenge yet... the celebration of Traveler Con!\n\nWatch Campaign 2, Episode 108 - “Traveler Con” youtu.be/YIcNZERTDOY pic.twitter.com/c3UfsYwNUv", 'timestamp': '18h', 'checked': False, 'key': '1303045370759577604'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Pyu✨ @ FE3H hellhole', 'handle': '@pyudraws', 'tweet': 'I miss miss reani 😔✊🏻 #criticalrole #CriticalRoleArt @MicaBurton pic.twitter.com/LdJoMz6qaB', 'timestamp': '21h', 'checked': False, 'key': '1303012984680329218'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'WEEKLY SCHEDULE ⚔️\n\nWhat new adventures await the Mighty Nein? Find out this Thursday with Critical Role Campaign 2, Episode 109! critrole.com/programming-sc…', 'timestamp': '20h', 'checked': False, 'key': '1303018963836731397'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'COSPLAY GALLERY (September 2020)\n\nFeatured cosplay by @fangirlcrafter critrole.com/cosplay-galler… pic.twitter.com/p0quL6edQB', 'timestamp': '21h', 'checked': False, 'key': '1303008993762095109'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'marcorio', 'handle': '@MarcoRio_jpg', 'tweet': '"What level?" "Nine."\n\nScanlan design inspired by @Takayuuki_art #criticalrolefanart #dnd #dnd5e pic.twitter.com/IVYSvgozby', 'timestamp': 'Sep 5', 'checked': False, 'key': '1302208173416226817'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'EeriePete', 'handle': '@EeriePete', 'tweet': "A Vex'ahlia outfit design #CriticalRole #CriticalRoleArt pic.twitter.com/SLbccutULA", 'timestamp': 'Sep 4', 'checked': False, 'key': '1301948003322740737'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Kaywinnit', 'handle': '@VratnaZdenka', 'tweet': 'His name is Caleb Widogast and he is on fire 🔥\nCosplay by @Withal_32 and photo by me 😎 #calebwidogast #calebcosplay #CriticalRole #criticalrolecosplay pic.twitter.com/HR6NhmQHFV', 'timestamp': 'Sep 2', 'checked': False, 'key': '1301064109144891392'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Marisha Ray', 'handle': '@Marisha_Ray', 'tweet': 'Friendly reminder of this PSA: You can mute hashtags and certain words on Twitter to avoid #CriticalRole spoilers. That’s easier than getting pouty at people who are enjoying discussing the show.', 'timestamp': 'Sep 4', 'checked': False, 'key': '1301933099484241921'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'In case you missed it live…\n\nTalks Machina will return on September 15th at 7pm Pacific with new episodes airing every other week! Get hyped for more banter from your faves. Oh! And @BrianWFoster will be there too. 😉 pic.twitter.com/cx8XDCS8h8', 'timestamp': 'Sep 4', 'checked': False, 'key': '1301935729975517184'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': "Tonight’s episode is #sponsored by @DnDBeyond ! Journey into Exandria this Labor Day weekend with Explorer's Guide to Wildemount and create your own rich backstory with their Heroic Chronicle. \n\nGrab your copy today at dndbeyond.link/critter ! pic.twitter.com/Dw6FwsCfOI", 'timestamp': 'Sep 3', 'checked': False, 'key': '1301736756686000128'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': "Tonight’s episode of Critical Role is #sponsored by @PetersenGames and their sourcebook Cthulhu Mythos Sagas: Dark Worlds. Use the promo code ‘Criticalrole' when you subscribe to save 20% on the rest of this epic adventure and more.\n\nCheck it out now at bit.ly/CRPetersenGames ! pic.twitter.com/V2vzGLq2J3", 'timestamp': 'Sep 3', 'checked': False, 'key': '1301705302379843584'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'Let chaos reign. 💚 pic.twitter.com/OpnMCZd5cR', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301701646351622144'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Matthew Mercer', 'handle': '@matthewmercer', 'tweet': 'Tonight’s #CriticalRole begins in about an hour!\n\nWith the village of Vo housing the droves of celebratory arrivals, the Mighty Nein prepares to host the event we’ve all be waiting for... Travelercon! Join us! Twitch.tv/criticalrole', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301685926595182593'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Dark Horse Comics', 'handle': '@DarkHorseComics', 'tweet': '☂️ ☂️ ☂️ ✨ \nNow THIS is an adventuring party. The Umbrella Academy Volumes 1, 2, & 3 AND Critical Role: Vox Machina Origins Vol. 2 all on the latest New York Times Best Sellers: Graphic Books & Manga. Congrats, all! nyti.ms/2QSLX01 #UmbrellaAcademy #CriticalRole pic.twitter.com/XGoUdfkQFe', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301648849392467968'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Wyrmwood', 'handle': '@WyrmwoodGaming', 'tweet': 'pic.twitter.com/g7zmFlXkxJ', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301626214034083842'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'LaTia, Overwhelmed™', 'handle': '@LaTiaJacquise', 'tweet': "oh my gosh you guys. \n\nYours truly is hopping into the DM's seat that Saturday at 12pm PST/2pm CST, and @ChrisPerkinsDnD , @quiddie , @CarlosCrits , @DoubleGXG , @Jody_Houser , and @VoiceOfOBrien have NO IDEA what they're about to get into.\n\nIt's gonna be SO. MUCH. FUN. twitter.com/Wizards_DnD/st…", 'timestamp': 'Sep 3', 'checked': False, 'key': '1301561719345602560'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Rachel McEwan', 'handle': '@RachelMcEwanArt', 'tweet': 'Just felt like drawing Yasha...again #CriticalRoleArt #Criticalrole #criticalrolefanart pic.twitter.com/WJU4DZYXuT', 'timestamp': 'Aug 30', 'checked': False, 'key': '1300132378648571904'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'Replying to @OutRightIntl $13 of each Don’t Forget to Love Each Other Shirt preordered in our Australia shop will benefit @OutRightIntl , an incredible nonprofit organization dedicated to fighting for the rights of LGBTQIA+ folks around the world. 🌈✨', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301550869935079426'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'MEGA MERCH ALERT!\n\nBehold our Tal’Dorei Republic Tank Top, Mighty Nein Puzzle by @TheOpGames (art: @LaurenWalshArt ), Chibi Veth pin (design: @asunnydisposish ), and our Don’t Forget to Love Each Other Shirt! shop.critrole.com shop.critrole.co.uk shop.critrole.com.au pic.twitter.com/SAiw1dmUkV', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301550724396900355'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'FAN ART GALLERY: Faerie Fyre Festival\n\nFeatured art by @ajmakesart critrole.com/fan-art-galler…', 'timestamp': 'Sep 3', 'checked': False, 'key': '1301535913856573440'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Irene', 'handle': '@FeebleExcuses', 'tweet': '"I look like me, but goth!"\n\nJester is from @CriticalRole and belongs to @LauraBaileyVO #cosplay #CriticalRole #CriticalRoleCosplay pic.twitter.com/QM4iBAPRov', 'timestamp': 'Sep 2', 'checked': False, 'key': '1301205082726379521'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': "Liam O'Brien", 'handle': '@VoiceOfOBrien', 'tweet': '3 hours left to the Wildlands KS! \nThe good folk over at @dwarvenforge are… almost… at.. the peak…\n\nOH GODS, WHAT IS THAT?!?!? kickstarter.com/projects/dwarv… pic.twitter.com/dYyNHRvWre', 'timestamp': 'Sep 2', 'checked': False, 'key': '1301276174631329793'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'In today’s #criticalrecap , our Lore Keeper @ItsDaniCarr describes the divine decisions of Campaign 2, Episode 107 - “Devoutness and Dicks” critrole.com/critical-recap…', 'timestamp': 'Sep 2', 'checked': False, 'key': '1301233784768036864'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'maali', 'handle': '@maalidoesart', 'tweet': 'Veth #art #CriticalRole #CriticalRoleArt #nottthebrave #mightynein @samriegel @CriticalRole pic.twitter.com/VPjnQDQzQ3', 'timestamp': 'Sep 2', 'checked': False, 'key': '1301127815975366658'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Zilai 🐋', 'handle': '@zilai', 'tweet': "I'm planning out a Keyleth drawing and wanted to try out a design. #criticalrolefanart #CriticalRole pic.twitter.com/1yVVHjlbmH", 'timestamp': 'Sep 1', 'checked': False, 'key': '1300801403221192706'},
    {'is_retweet': True, 'header': 'Critical Role retweeted', 'name': 'Amy Lane', 'handle': '@AmyLaneDraws', 'tweet': "Through Rumblecusp. \nIt's been a while since I drew the whole gang and I love them so here you go. #CriticalRoleArt #CriticalRoleFanart #Criticalrole pic.twitter.com/wFCvTWp5Bv", 'timestamp': 'Sep 1', 'checked': False, 'key': '1300869490092191744'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'Did you know that you (YES YOU!) can be featured in our monthly cosplay gallery? All skill levels are welcome and of course, diverse cosplayer submissions are encouraged! \n\nSubmit your cosplays by visiting critrole.com/submit Cosplay by @Riyuski ||📸 by @Minomotu pic.twitter.com/0MPwKb90o9', 'timestamp': 'Aug 31', 'checked': False, 'key': '1300582148441743360'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': "The Mighty Nein's combat from Episode 107 was #sponsored by our pals at @dwarvenforge . There are still TWO DAYS left to go on their epic 8th Kickstarter featuring a fantastic collection of wilderness gaming terrain. \n\nCheck it out now at: dwarvenforge.com/wildlands pic.twitter.com/GQkwxCxEff", 'timestamp': 'Aug 31', 'checked': False, 'key': '1300559005920768002'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'Wido*GASP* this is incredible! 🔥 twitter.com/matthubelart/s…', 'timestamp': 'Aug 31', 'checked': False, 'key': '1300542258396106753'},
    {'is_retweet': False, 'header': '', 'name': 'Critical Role', 'handle': '@CriticalRole', 'tweet': 'With less than a week until Traveler Con, the Mighty Nein put on their party planning hats to prep Rumblecusp for the unruly event.\n\nWatch Campaign 2, Episode 107 - “Devoutness and Dicks” youtu.be/dd8jt0jfeww pic.twitter.com/1ZIiYRZ8Z3', 'timestamp': 'Aug 31', 'checked': False, 'key': '1300508805390721025'}]

  for i in range(0,30):
    assert((k in tweets[i] and should_be[i][k] == v) for k, v in should_be[i].items())